Business Questions
Which vehicle characteristics have the greatest influence on the listing price of a used car?
How do factors such as mileage, age, accident history, and horsepower affect a vehicle's listing price?
Can a multiple linear regression model accurately estimate the listing price of a used vehicle based on its characteristics?
Can the model identify vehicles whose asking price appears significantly higher or lower than the estimated market value?

In [3]:
import pandas as pd
df = pd.read_csv("../data/processed/used_cars_reduced.csv")

C:\Users\casey\AppData\Local\Temp\ipykernel_46396\1083013566.py:2: DtypeWarning: Columns (0: dealer_zip) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/used_cars_reduced.csv")

In [36]:
df.drop_duplicates(inplace = True)

In [38]:
df = df.reset_index()

In [39]:
df.shape

(2663251, 23)

In [20]:
df.columns

Index(['city', 'dealer_zip', 'engine_cylinders', 'engine_type',
       'frame_damaged', 'fuel_type', 'has_accidents', 'horsepower', 'is_new',
       'make_name', 'mileage', 'model_name', 'owner_count', 'price', 'salvage',
       'seller_rating', 'transmission', 'trim_name', 'vehicle_damage_category',
       'wheel_system', 'year'],
      dtype='str')

In [40]:
df.tail()

,level_0,index,city,dealer_zip,engine_cylinders,engine_type,frame_damaged,fuel_type,has_accidents,horsepower,...,model_name,owner_count,price,salvage,seller_rating,transmission,trim_name,vehicle_damage_category,wheel_system,year
2663246,2663246,3000035,Fairfield,94533,I4,I4,False,Gasoline,False,170.0,...,Equinox,1.0,17998.0,False,4.272727,A,1.5T LT FWD,NaN,FWD,2018
2663247,2663247,3000036,Vallejo,94591,V6,V6,NaN,Gasoline,NaN,310.0,...,Traverse,NaN,36490.0,NaN,4.533333,A,LS FWD,NaN,FWD,2020
2663248,2663248,3000037,Napa,94559,NaN,NaN,False,NaN,True,240.0,...,Fusion,2.0,12990.0,False,4.142857,A,SE,NaN,FWD,2016
2663249,2663249,3000038,Fairfield,94533,I4 Diesel,I4 Diesel,False,Diesel,False,180.0,...,XE,1.0,26998.0,False,4.272727,A,20d Premium AWD,NaN,AWD,2017
2663250,2663250,3000039,Napa,94559,I4,I4,False,Gasoline,False,170.0,...,Rogue,1.0,19900.0,False,4.333333,A,2017.5 SV FWD,NaN,FWD,2017

In [28]:
df.dtypes

city                           str
dealer_zip                  object
engine_cylinders               str
engine_type                    str
frame_damaged               object
fuel_type                      str
has_accidents               object
horsepower                 float64
is_new                        bool
make_name                      str
mileage                    float64
model_name                     str
owner_count                float64
price                      float64
salvage                     object
seller_rating              float64
transmission                   str
trim_name                      str
vehicle_damage_category    float64
wheel_system                   str
year                         int64
dtype: object

In [29]:
df.isna().sum()

city                             0
dealer_zip                       0
engine_cylinders             87917
engine_type                  87917
frame_damaged              1096177
fuel_type                    72638
has_accidents              1096177
horsepower                  150591
is_new                           0
make_name                        0
mileage                     102516
model_name                       0
owner_count                1181157
price                            0
salvage                    1096177
seller_rating                38300
transmission                 55013
trim_name                   103002
vehicle_damage_category    2663251
wheel_system                128034
year                             0
dtype: int64

In [30]:
df.shape

(2663251, 21)

In [33]:
df.describe()

,horsepower,mileage,owner_count,price,seller_rating,vehicle_damage_category,year
count,2.512660e+06,2.560735e+06,1.482094e+06,2.663251e+06,2.624951e+06,0.0,2.663251e+06
mean,2.516716e+02,3.473086e+04,1.532872e+00,2.972489e+04,4.280726e+00,NaN,2.017427e+03
std,9.103464e+01,7.796758e+04,9.204841e-01,2.025110e+04,5.112244e-01,NaN,4.339633e+00
min,5.500000e+01,0.000000e+00,1.000000e+00,1.650000e+02,1.000000e+00,NaN,1.915000e+03
25%,1.760000e+02,9.000000e+00,1.000000e+00,1.768100e+04,4.027778e+00,NaN,2.017000e+03
50%,2.480000e+02,1.788000e+04,1.000000e+00,2.600000e+04,4.352941e+00,NaN,2.019000e+03
75%,3.050000e+02,4.924100e+04,2.000000e+00,3.829000e+04,4.615385e+00,NaN,2.020000e+03
max,1.001000e+03,9.999999e+07,1.900000e+01,3.299995e+06,5.000000e+00,NaN,2.021000e+03

In [43]:
df.drop(columns=["level_0", "index"], inplace=True)

In [45]:
df.head()

,city,dealer_zip,engine_cylinders,engine_type,frame_damaged,fuel_type,has_accidents,horsepower,is_new,make_name,...,model_name,owner_count,price,salvage,seller_rating,transmission,trim_name,vehicle_damage_category,wheel_system,year
0,Bayamon,960,I4,I4,NaN,Gasoline,NaN,177.0,True,Jeep,...,Renegade,NaN,23141.0,NaN,2.8,A,Latitude FWD,NaN,FWD,2019
1,San Juan,922,I4,I4,NaN,Gasoline,NaN,246.0,True,Land Rover,...,Discovery Sport,NaN,46500.0,NaN,3.0,A,S AWD,NaN,AWD,2020
2,Guaynabo,969,H4,H4,False,Gasoline,False,305.0,False,Subaru,...,WRX STI,3.0,46995.0,False,NaN,M,Base,NaN,AWD,2016
3,San Juan,922,V6,V6,NaN,Gasoline,NaN,340.0,True,Land Rover,...,Discovery,NaN,67430.0,NaN,3.0,A,V6 HSE AWD,NaN,AWD,2020
4,San Juan,922,I4,I4,NaN,Gasoline,NaN,246.0,True,Land Rover,...,Discovery Sport,NaN,48880.0,NaN,3.0,A,S AWD,NaN,AWD,2020

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2663251 entries, 0 to 2663250
Data columns (total 21 columns):
 #   Column                   Dtype
---  ------                   -----
 0   city                     str
 1   dealer_zip               object
 2   engine_cylinders         str
 3   engine_type              str
 4   frame_damaged            object
 5   fuel_type                str
 6   has_accidents            object
 7   horsepower               float64
 8   is_new                   bool
 9   make_name                str
 10  mileage                  float64
 11  model_name               str
 12  owner_count              float64
 13  price                    float64
 14  salvage                  object
 15  seller_rating            float64
 16  transmission             str
 17  trim_name                str
 18  vehicle_damage_category  float64
 19  wheel_system             str
 20  year                     int64
dtypes: bool(1), float64(6), int64(1), object(4), str(9)
memory usage: 408.9+ MB